---
- name: Directories permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: p2p
    group: p2p
  with_items:
    - "{{ sonarr_downloads }}"

- name: Configure optional network links (sonarr)
  set_fact:
    sonarr_network_links: "{{ sonarr_network_links | default([]) }} + [item]"
  with_items:
    - rtorrent:rtorrent
  when: use_containers.rtorrent

- name: Configure optional network links (sonarr)
  set_fact:
    sonarr_network_links: "{{ sonarr_network_links | default([]) }} + [item]"
  with_items:
    - jackett:jackett
  when: use_containers.jackett

- name: Sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    state: started
    hostname: sonarr
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    volumes:
      - "/etc/sonarr:/config"
      - "{{ medias_root }}:/p2p"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    purge_networks: yes
    networks:
      - name: p2p
        links: "{{ sonarr_network_links }}"
    labels:
      traefik.docker.network: "p2p"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:sonarr.{{ domain }}"
      traefik.basic.port: "8989"
